2022-03-26 21:27:48,716 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-26 21:27:48,716 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\91876\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2022-03-26 21:27:48,716 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-26 21:27:49,233 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-03-26 21:27:49,234 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-03-26 21:27:49,236 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-03-26 21:27:49,237 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2022-03-26 21:32:50,070 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2022-03-26 21:32:50,070 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"","status":"fail"}'
2022-03-26 21:32:50,070 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-26 21:32:50,086 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: 
2022-03-26 21:32:50,087 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: {}
2022-03-26 21:32:50,664 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-26 21:32:51,310 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-26 21:32:51,908 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-26 21:32:55,395 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-26 21:32:55,395 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXGqM-4OZMu_6HwjrK9LpecjJw7Z1H1IXBa3hRWopjzy9ha7YTxaWYbPm6qEmEBglU8rrq8/mw5gxT6H9ltcoO24/","api_path":"/challenge/AXGqM-4OZMu_6HwjrK9LpecjJw7Z1H1IXBa3hRWopjzy9ha7YTxaWYbPm6qEmEBglU8rrq8/mw5gxT6H9ltcoO24/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-26 21:32:55,411 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-26 21:32:55,411 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-26 21:32:55,411 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-03-26 21:32:55,413 - instabot version: 0.117.0 (api) - CRITICAL - Not logged in!
